name: Publish Docker Images

on:
  push:
    branches: [ master ]
    paths:
      # Paths that trigger a docker image build
      - 'etc/**'
      - 'share/**'
      - 'docker-entrypoint.sh'
      - 'Dockerfile'

jobs:
  feature:
    name: Build Zeek feature release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1
      with:
        repository: activecm/zeek
        tags: latest,3.2,3.2.3
        build_args: ZEEK_VERSION=3.2.3
        cache_froms: activecm/zeek:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

  lts:
    name: Build Zeek LTS release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1
      with:
        repository: activecm/zeek
        tags: lts,3,3.0,3.0.12
        build_args: ZEEK_VERSION=3.0.12
        cache_froms: activecm/zeek:lts
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}